"use strict";
var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
Object.defineProperty(exports, "__esModule", { value: true });
var styled_components_1 = require("styled-components");
exports.configureBaseStyle = function (config, injected) { return styled_components_1.createGlobalStyle(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n\n  ", ";\n\n  h1 { ", "; }\n  h2 { ", "; }\n  h3 { ", "; }\n  h4 { ", "; }\n  h5 { ", "; }\n  h6 { ", "; }\n  p { ", "; }\n  a { ", ";  }\n  span { ", "; }\n  button { ", "; }\n  div { ", "; }\n\n  h1, h2, h3, h4, h5, h6, li, p, a, span {\n    margin: 0;\n  }\n\n  * {\n    box-sizing: border-box;\n    -webkit-overflow-scrolling: touch\n  }\n\n\n  body {\n    overflow-x: hidden;\n    overflow-y: auto;\n  }\n\n  body, html, #root {\n    margin: 0;\n    flex-direction: column;\n    display: flex;\n    flex: 1;\n    padding: 0;\n  }\n\n  body {\n    overflow-y: scroll;\n  }\n\n  input::-webkit-outer-spin-button,\n  input::-webkit-inner-spin-button {\n    -webkit-appearance: none;\n    margin: 0;\n  }\n\n  /* Firefox */\n  input[type=number] {\n    -moz-appearance: textfield;\n  }\n"], ["\n\n  ", ";\n\n  h1 { ", "; }\n  h2 { ", "; }\n  h3 { ", "; }\n  h4 { ", "; }\n  h5 { ", "; }\n  h6 { ", "; }\n  p { ", "; }\n  a { ", ";  }\n  span { ", "; }\n  button { ", "; }\n  div { ", "; }\n\n  h1, h2, h3, h4, h5, h6, li, p, a, span {\n    margin: 0;\n  }\n\n  * {\n    box-sizing: border-box;\n    -webkit-overflow-scrolling: touch\n  }\n\n\n  body {\n    overflow-x: hidden;\n    overflow-y: auto;\n  }\n\n  body, html, #root {\n    margin: 0;\n    flex-direction: column;\n    display: flex;\n    flex: 1;\n    padding: 0;\n  }\n\n  body {\n    overflow-y: scroll;\n  }\n\n  input::-webkit-outer-spin-button,\n  input::-webkit-inner-spin-button {\n    -webkit-appearance: none;\n    margin: 0;\n  }\n\n  /* Firefox */\n  input[type=number] {\n    -moz-appearance: textfield;\n  }\n"])), injected, config.h1, config.h2, config.h3, config.h4, config.h5, config.h6, config.p, config.a, config.span, config.button, config.div); };
var templateObject_1;
//# sourceMappingURL=configure.style.js.map